Flowpack:
  JobQueue:
    Doctrine:
      testing:
        # Set to TRUE to enable functional testing against a database server and adjust backendOptions
        enabled: FALSE
#        backendOptions:
#          driver: 'pdo_mysql'
#          host: NULL
#          dbname: NULL
#          user: NULL
#          password: NULL
#          charset: 'utf8'
